apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: private-service-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.54.0/23
  avoidBuggyIPs: true
  serviceAllocation:
    priority: 50
    serviceSelectors:
      - matchExpressions:
          - {key: service, operator: In, values: [private]}
