---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: llm
spec:
  chart:
    spec:
      chart: ollama
      sourceRef:
        kind: HelmRepository
        name: ollama-helm
        namespace: flux-system
  interval: 5m
  timeout: 5m
  releaseName: ollama
  targetNamespace: llm
  valuesFrom:
  - kind: ConfigMap
    name: ollama-helm-chart-value-overrides
    valuesKey: values.yaml # This is the default, but best to be explicit for clarity






