---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: config-dns
  namespace: dns
resources:
- helm-release.yaml
- helm-repository.yaml
- external-dns.yaml

configMapGenerator:
- name: pihole-helm-chart-value-overrides
  namespace: dns
  files:
  - values.yaml
configurations:
  - kustomizeconfig.yaml
