---
# Source: owncast/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: owncast
  namespace: default
  labels:
    app.kubernetes.io/instance: owncast
    app.kubernetes.io/name: owncast
    app.kubernetes.io/version: 0.2.3
    service: private
  annotations:
    metallb.universe.tf/allow-shared-ip: owncast-svc
    external-dns.alpha.kubernetes.io/hostname: owncast.default.svc.talos-test01.kube.cluster.homelab.internal
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: owncast
    app.kubernetes.io/instance: owncast
---
# Source: owncast/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: owncast-rtmp
  namespace: default
  labels:
    app.kubernetes.io/instance: owncast
    app.kubernetes.io/name: owncast
    app.kubernetes.io/version: 0.2.3
    service: private
  annotations:
    metallb.universe.tf/allow-shared-ip: owncast-svc
    external-dns.alpha.kubernetes.io/hostname: owncast-rtmp.default.svc.talos-test01.kube.cluster.homelab.internal
spec:
  type: LoadBalancer
  ports:
  - port: 1935
    targetPort: 1935
    protocol: TCP
    name: rtmp
  selector:
    app.kubernetes.io/name: owncast
    app.kubernetes.io/instance: owncast
---
# Source: owncast/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: owncast
  namespace: default
  labels:
    app.kubernetes.io/instance: owncast
    app.kubernetes.io/name: owncast
    app.kubernetes.io/version: 0.2.3
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: owncast
      app.kubernetes.io/instance: owncast
  template:
    metadata:
      labels:
        app.kubernetes.io/name: owncast
        app.kubernetes.io/instance: owncast
    spec:
      
      serviceAccountName: default
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: owncast
          image: "gabekangas/owncast:0.2.3"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: rtmp
              containerPort: 1935
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5


---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: owncast-talos-test01-cluster-tunnel-lanealucy
  namespace: default
subjects:
  - name: owncast
tunnelRef:
  kind: ClusterTunnel
  name: talos-test01-cluster-tunnel-lanealucy
