apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/metallb/metallb
  ref:
    tag: v0.14.8
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-system
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: metallb-system
  sourceRef:
    kind: GitRepository
    name: metallb
  path: "./config/native"
  prune: true
  timeout: 2m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config-metallb-system
  namespace: flux-system
spec:
  interval: 5m
  dependsOn: 
    - name: metallb-system  
  path: ./config/talos-test01/configs/metallb-system
  prune: true # remove any elements later removed from the above path
  timeout: 2m # if not set, this defaults to interval duration, which is 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: controller
      namespace: metallb-system
