apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cloudflare-operator
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/adyanth/cloudflare-operator
  ref:
    tag: v0.10.4
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-operator-system
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: cloudflare-operator
  path: "./config/default"
  prune: true
  timeout: 2m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config-cloudflare-operator
  namespace: flux-system
spec:
  interval: 5m
  dependsOn: 
    - name: cloudflare-operator-system  
  path: ./config/talos-test01/configs/cloudflare-operator
  prune: true # remove any elements later removed from the above path
  timeout: 2m # if not set, this defaults to interval duration, which is 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
